// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MessageCode int32

const (
	// -- test --
	MessageCode_OPTest MessageCode = 0
	// -- 通用 : 1-500 --
	MessageCode_OPPing  MessageCode = 1
	MessageCode_OPPong  MessageCode = 2
	MessageCode_OPClose MessageCode = 3
)

var MessageCode_name = map[int32]string{
	0: "OPTest",
	1: "OPPing",
	2: "OPPong",
	3: "OPClose",
}
var MessageCode_value = map[string]int32{
	"OPTest":  0,
	"OPPing":  1,
	"OPPong":  2,
	"OPClose": 3,
}

func (x MessageCode) Enum() *MessageCode {
	p := new(MessageCode)
	*p = x
	return p
}
func (x MessageCode) String() string {
	return proto.EnumName(MessageCode_name, int32(x))
}
func (x *MessageCode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MessageCode_value, data, "MessageCode")
	if err != nil {
		return err
	}
	*x = MessageCode(value)
	return nil
}
func (MessageCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_common_83f4e6e3ec87edd0, []int{0}
}

// HTTP 请求返回头
type HTTPResponse struct {
	Result               *int32   `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	Msg                  *string  `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HTTPResponse) Reset()         { *m = HTTPResponse{} }
func (m *HTTPResponse) String() string { return proto.CompactTextString(m) }
func (*HTTPResponse) ProtoMessage()    {}
func (*HTTPResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_83f4e6e3ec87edd0, []int{0}
}
func (m *HTTPResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HTTPResponse.Unmarshal(m, b)
}
func (m *HTTPResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HTTPResponse.Marshal(b, m, deterministic)
}
func (dst *HTTPResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HTTPResponse.Merge(dst, src)
}
func (m *HTTPResponse) XXX_Size() int {
	return xxx_messageInfo_HTTPResponse.Size(m)
}
func (m *HTTPResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HTTPResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HTTPResponse proto.InternalMessageInfo

func (m *HTTPResponse) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *HTTPResponse) GetMsg() string {
	if m != nil && m.Msg != nil {
		return *m.Msg
	}
	return ""
}

func (m *HTTPResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// 消息头
type Message struct {
	Cmd                  *MessageCode `protobuf:"varint,1,req,name=cmd,enum=pb.MessageCode" json:"cmd,omitempty"`
	Data                 []byte       `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
	ErrCode              *int32       `protobuf:"varint,3,opt,name=errCode" json:"errCode,omitempty"`
	ErrMsg               *string      `protobuf:"bytes,4,opt,name=errMsg" json:"errMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_83f4e6e3ec87edd0, []int{1}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (dst *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(dst, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetCmd() MessageCode {
	if m != nil && m.Cmd != nil {
		return *m.Cmd
	}
	return MessageCode_OPTest
}

func (m *Message) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Message) GetErrCode() int32 {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return 0
}

func (m *Message) GetErrMsg() string {
	if m != nil && m.ErrMsg != nil {
		return *m.ErrMsg
	}
	return ""
}

// 心跳消息
type HeartBeat struct {
	NowTime              *int32   `protobuf:"varint,1,req,name=nowTime" json:"nowTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartBeat) Reset()         { *m = HeartBeat{} }
func (m *HeartBeat) String() string { return proto.CompactTextString(m) }
func (*HeartBeat) ProtoMessage()    {}
func (*HeartBeat) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_83f4e6e3ec87edd0, []int{2}
}
func (m *HeartBeat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartBeat.Unmarshal(m, b)
}
func (m *HeartBeat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartBeat.Marshal(b, m, deterministic)
}
func (dst *HeartBeat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartBeat.Merge(dst, src)
}
func (m *HeartBeat) XXX_Size() int {
	return xxx_messageInfo_HeartBeat.Size(m)
}
func (m *HeartBeat) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartBeat.DiscardUnknown(m)
}

var xxx_messageInfo_HeartBeat proto.InternalMessageInfo

func (m *HeartBeat) GetNowTime() int32 {
	if m != nil && m.NowTime != nil {
		return *m.NowTime
	}
	return 0
}

func init() {
	proto.RegisterType((*HTTPResponse)(nil), "pb.HTTPResponse")
	proto.RegisterType((*Message)(nil), "pb.Message")
	proto.RegisterType((*HeartBeat)(nil), "pb.HeartBeat")
	proto.RegisterEnum("pb.MessageCode", MessageCode_name, MessageCode_value)
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_common_83f4e6e3ec87edd0) }

var fileDescriptor_common_83f4e6e3ec87edd0 = []byte{
	// 224 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0xcd, 0x31, 0x6b, 0xc3, 0x30,
	0x10, 0x05, 0xe0, 0xca, 0x8e, 0x63, 0x72, 0x16, 0x89, 0xd1, 0xa4, 0x21, 0x83, 0xf1, 0x64, 0x3a,
	0x78, 0xe8, 0xd6, 0xa5, 0x43, 0xb3, 0x64, 0x09, 0x31, 0xc5, 0x74, 0x57, 0xe2, 0x43, 0x04, 0x22,
	0x9d, 0xd1, 0xa9, 0xf4, 0xef, 0x17, 0xa5, 0xa6, 0x74, 0x7b, 0xf0, 0xee, 0xbe, 0x07, 0xf2, 0x4a,
	0xce, 0x91, 0xef, 0xe7, 0x40, 0x91, 0x54, 0x36, 0x5f, 0xda, 0x57, 0x90, 0xc7, 0x71, 0x1c, 0x3e,
	0x90, 0x67, 0xf2, 0x8c, 0x6a, 0x0b, 0xeb, 0x80, 0xfc, 0x75, 0x8f, 0x5a, 0x34, 0xa2, 0x2b, 0x54,
	0x05, 0xb9, 0x63, 0xab, 0xb3, 0x46, 0x74, 0x1b, 0x25, 0x61, 0x35, 0x99, 0x68, 0x74, 0xde, 0x88,
	0x4e, 0xb6, 0x9f, 0x50, 0x9e, 0x90, 0xd9, 0x58, 0x54, 0x7b, 0xc8, 0xaf, 0x6e, 0xd2, 0xa2, 0xc9,
	0xba, 0xed, 0xcb, 0xae, 0x9f, 0x2f, 0xfd, 0xd2, 0x1c, 0x68, 0xc2, 0xbf, 0xb7, 0x84, 0x48, 0xb5,
	0x83, 0x12, 0x43, 0x48, 0xc5, 0xc3, 0x29, 0xd2, 0x24, 0x86, 0x70, 0x62, 0xab, 0x57, 0x69, 0xa5,
	0xdd, 0xc3, 0xe6, 0x88, 0x26, 0xc4, 0x77, 0x34, 0x31, 0x5d, 0x7b, 0xfa, 0x1e, 0x6f, 0x0e, 0x1f,
	0x7a, 0xf1, 0xfc, 0x06, 0xd5, 0x7f, 0x1b, 0x60, 0x7d, 0x1e, 0x46, 0xe4, 0x58, 0x3f, 0xfd, 0xe6,
	0xe1, 0xe6, 0x6d, 0x2d, 0x96, 0x4c, 0xde, 0xd6, 0x99, 0xaa, 0xa0, 0x3c, 0x0f, 0x87, 0x3b, 0x31,
	0xd6, 0xf9, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc0, 0x5f, 0x26, 0x09, 0x03, 0x01, 0x00, 0x00,
}
